// Constantes de producción para formularios y validaciones

export const ETAPAS_PRODUCCION = [
  "PREPARACION",
  "MACERADO",
  "COCCION",
  "FERMENTACION",
  "MADURACION",
  "FILTRADO",
  "ENVASADO",
  "CONTROL_CALIDAD",
] as const;

export const PARAMETROS_POR_ETAPA = {
  PREPARACION: ["TEMPERATURA_AGUA", "PH_AGUA", "DUREZA_AGUA", "CLORO_RESIDUAL"],
  MACERADO: ["TEMPERATURA", "PH", "TIEMPO_REPOSO", "DENSIDAD"],
  COCCION: ["TEMPERATURA", "TIEMPO_COCCION", "PRESION", "HUMEDAD"],
  FERMENTACION: [
    "TEMPERATURA",
    "PH",
    "DENSIDAD",
    "GRADO_ALCOHOL",
    "AZUCARES_RESIDUALES",
  ],
  MADURACION: ["TEMPERATURA", "PRESION", "TIEMPO", "CO2_DISUELTO"],
  FILTRADO: ["PRESION", "CAUDAL", "TURBIDEZ", "TEMPERATURA"],
  ENVASADO: ["TEMPERATURA", "PRESION_LLENADO", "NIVEL_LLENADO", "HERMETICIDAD"],
  CONTROL_CALIDAD: [
    "PH_FINAL",
    "GRADO_ALCOHOL_FINAL",
    "AMARGOR",
    "COLOR",
    "TURBIDEZ_FINAL",
  ],
} as const;

export const UNIDADES_MEDIDA = [
  "CELSIUS",
  "FAHRENHEIT",
  "PH",
  "DENSIDAD_RELATIVA",
  "GRADO_ALCOHOL",
  "PRESION_BAR",
  "PRESION_PSI",
  "MINUTOS",
  "HORAS",
  "LITROS_HORA",
  "ML_MIN",
  "PPM",
  "PORCENTAJE",
  "IBU",
  "EBC",
  "NTU",
] as const; 